name: airshield
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.14.2"
  http: ^1.2.2
  awesome_dialog: ^3.2.1
  searchfield: ^1.3.5
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_database: ^11.2.0
  firebase_auth: ^5.3.4
  shared_preferences: ^2.5.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_channel_ios: true
  adaptive_icon_background: "#1e3a8a"
  adaptive_icon_foreground: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
