// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi6l_n5ScTQ7G7eM5uP_CmMFWuccODlbI',
    appId: '1:824739029067:web:83725993dd9ba13961edce',
    messagingSenderId: '824739029067',
    projectId: 'airshield-ccbb3',
    authDomain: 'airshield-ccbb3.firebaseapp.com',
    storageBucket: 'airshield-ccbb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIUUhZc0n6QechStJZwxj3V6DOLnVaK4g',
    appId: '1:824739029067:android:77344b27ae415e3d61edce',
    messagingSenderId: '824739029067',
    projectId: 'airshield-ccbb3',
    storageBucket: 'airshield-ccbb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIcBnOVpGUk451paUn4GaDgAOsJLNdxpY',
    appId: '1:824739029067:ios:2d992a148075742661edce',
    messagingSenderId: '824739029067',
    projectId: 'airshield-ccbb3',
    storageBucket: 'airshield-ccbb3.firebasestorage.app',
    iosBundleId: 'com.example.airshield',
  );
}
